[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
native = "C5pqRkE3So12oijp44sMEf3MmNMYUrYFqBS9KotXhycs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
