[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_htlc = "3TTb3BF3H273DS8hCJT9w8wuhtchN7fi7tX2sZDZ3p3Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
